/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.*;

public class App {
  public static void main(String[] args) {
    JFrame jf = new JFrame("Okno");
    jf.setSize(400, 300);
    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    jf.setVisible(true);
  }
}
